version: "3.9"

services:
  db:
    image: ankane/pgvector:latest  # ✅ Soporte para extensión vector()
    container_name: reconocimiento-db
    restart: always
    environment:
      POSTGRES_DB: SCOUT_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: reconocimiento-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  django:
    build:
      context: .
    container_name: reconocimiento-django
    command: >
      bash -c "
      until pg_isready -h db -U postgres; do
        echo 'Esperando a que PostgreSQL esté listo...';
        sleep 2;
      done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=reconocimiento.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  rabbitmq_data:
