# Generated by Django 5.2.2 on 2025-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_carrera'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='sedes.asignatura'),
        ),
    ]
