# Generated by Django 5.2.2 on 2025-06-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='motivo_cambio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
