# Generated by Django 5.2 on 2025-06-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_imagen_customuser_motivo_cambio'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='sedes.seccion'),
        ),
    ]
