# Generated by Django 5.2.2 on 2025-06-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_seccion'),
        ('sedes', '0002_alter_carrera_options_alter_carrera_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='sedes.sede')),
            ],
        ),
        migrations.CreateModel(
            name='SemanaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('clases', 'Clases'), ('receso', 'Receso'), ('examenes', 'Exámenes'), ('feriado', 'Feriado')], default='clases', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='core.calendarioacademico')),
            ],
        ),
    ]
