# Generated by Django 5.2.2 on 2025-06-16 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-es_principal', '-fecha_creacion'],
            },
        ),
    ]
