# Generated by Django 5.2 on 2025-06-24 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('camara_ip', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado')], max_length=2)),
                ('publicada', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.aula')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.bloquehorario')),
                ('profesor', models.ForeignKey(limit_choices_to={'user_type': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('finalizada', models.BooleanField(default=False)),
                ('semana_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semanaacademica')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.claseinstancia')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField()),
                ('manual', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'user_type': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.claseinstancia')),
            ],
            options={
                'unique_together': {('instancia', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='ClasePlantillaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('effective_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semanaacademica')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clases.clase')),
            ],
        ),
        migrations.AddField(
            model_name='claseinstancia',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='clases.claseplantillaversion'),
        ),
        migrations.CreateModel(
            name='HistorialAsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clases.asistenciaclase')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='claseinstancia',
            unique_together={('version', 'semana_academica')},
        ),
    ]
