# Generated by Django 5.2 on 2025-06-14 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=10)),
                ('ip_camara', models.CharField(blank=True, help_text='Puede estar vacía si se usa webcam local', max_length=100)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.asignatura')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.aula')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.bloquehorario')),
                ('profesor', models.ForeignKey(limit_choices_to={'user_type': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.seccion')),
            ],
        ),
    ]
