# Generated by Django 5.2 on 2025-06-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sedes.sede'),
            preserve_default=False,
        ),
    ]
