# Generated by Django 5.2 on 2025-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_aula_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='camara_ip',
            field=models.CharField(blank=True, default='0', help_text='URL de la cámara o "0" para usar la cámara local', max_length=200),
        ),
    ]
