# Generated by Django 5.2 on 2025-06-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_bloquehorario_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquehorario',
            name='dia_semana',
        ),
    ]
