# Generated by Django 5.2 on 2025-06-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_remove_bloquehorario_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='asignatura',
        ),
    ]
