# Generated by Django 5.2 on 2025-06-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_remove_aula_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha',
        ),
    ]
