# Generated by Django 5.2.2 on 2025-06-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_remove_clase_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='dia_semana',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], default='LU', max_length=2),
            preserve_default=False,
        ),
    ]
