# Generated by Django 5.2.2 on 2025-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_alter_clase_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia_semana',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=12),
        ),
    ]
