# Generated by Django 5.2.2 on 2025-06-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_alter_clase_dia_semana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('modo', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.clase')),
                ('estudiante', models.ForeignKey(limit_choices_to={'user_type': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clase', 'estudiante')},
            },
        ),
    ]
