# Generated by Django 5.2.2 on 2025-06-18 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0009_asistenciaclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaclase',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='asistenciaclase',
            name='modo',
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
