# Generated by Django 5.2.2 on 2025-06-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0010_remove_asistenciaclase_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='consolidada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
