# Generated by Django 5.2.2 on 2025-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0012_historialasistenciaclase_auditoriaasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='ausentes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clase',
            name='porcentaje_asistencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clase',
            name='presentes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clase',
            name='total_estudiantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
