# Generated by Django 5.2.2 on 2025-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0013_clase_ausentes_clase_porcentaje_asistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
