# Generated by Django 5.2.2 on 2025-06-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0014_alter_clase_fecha'),
        ('core', '0006_calendarioacademico_semanaacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='semana_academica',
            field=models.ForeignKey(blank=True, help_text='Semana académica a la que corresponde la clase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='core.semanaacademica'),
        ),
    ]
