# Generated by Django 5.2.2 on 2025-06-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0015_clase_semana_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
