# Generated by Django 5.2 on 2025-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('nombre', 'sede')},
        ),
    ]
