# Generated by Django 5.2.2 on 2025-06-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
