# Generated by Django 5.2.2 on 2025-06-30 00:36

import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_recreate_embedding_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantefoto',
            options={'ordering': ['-es_base', '-created_at']},
        ),
        migrations.RenameField(
            model_name='estudiantefoto',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='estudiantefoto',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantefoto',
            unique_together={('estudiante', 'es_base')},
        ),
    ]
