# Generated by Django 5.2.2 on 2025-06-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_delete_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='seccion',
        ),
        migrations.CreateModel(
            name='EstudianteAsignaturaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.seccion')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura')},
            },
        ),
    ]
