# Generated by Django 5.2.2 on 2025-06-30 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_estudiantefoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudiantefoto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='estudiantefoto',
            constraint=models.UniqueConstraint(condition=models.Q(('es_base', True)), fields=('estudiante',), name='unique_foto_base_per_estudiante'),
        ),
    ]
