# Generated by Django 5.2 on 2025-06-14 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_estudianteasignaturaseccion_estudiante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_seccion', to=settings.AUTH_USER_MODEL),
        ),
    ]
