# Generated by Django 5.2.2 on 2025-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_estudiantefoto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantefoto',
            name='es_dinamica',
            field=models.BooleanField(default=False),
        ),
    ]
