# Generated by Django 5.2.2 on 2025-07-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_estudiantefoto_es_dinamica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantefoto',
            name='es_dinamica',
        ),
    ]
