# Generated by Django 5.2.2 on 2025-06-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_estudianteasignaturaseccion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_seccion', to='personas.seccion'),
        ),
    ]
