# Generated by Django 5.2.2 on 2025-06-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_estudianteasignaturaseccion_seccion'),
        ('sedes', '0002_alter_carrera_options_alter_carrera_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_estudiantes_asignatura', to='sedes.carrera'),
        ),
    ]
