# Generated by Django 5.2.2 on 2025-06-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_alter_asignatura_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_estudiantes_asignatura', to='personas.seccion'),
        ),
    ]
