# Generated by Django 5.2.2 on 2025-06-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_alter_estudianteasignaturaseccion_seccion'),
        ('sedes', '0002_alter_carrera_options_alter_carrera_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='asignatura',
        ),
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.asignatura'),
        ),
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_asignatura', to='sedes.seccion'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
