# Generated by Django 5.2.2 on 2025-06-15 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_remove_seccion_asignatura_and_more'),
        ('sedes', '0002_alter_carrera_options_alter_carrera_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_asignatura_seccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudianteasignaturaseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_estudiantes_asignatura', to='sedes.seccion'),
        ),
    ]
